### ISSUE TITLE
Unknown Spell on Monks

### ISSUE THREAD

**Issue by EthanCentaurai** [Adirelle/oUF_Adirelle#10]
Hello,

Monks appear to no longer have the Legacy of the Emperor ability in 7.0.3 which causes this error on logging in:

`1x XRange:CheckSpell: unknown spell1 #115921 oUF_Adirelle\elements\XRange.lua:150: in function <oUF_Adirelle\elements\XRange.lua:31> oUF_Adirelle\elements\XRange.lua:225: in function <oUF_Adirelle\elements\XRange.lua:224> oUF_Adirelle\elements\XRange.lua:238: in function 'enable' oUF_Adirelle\oUF\ouf.lua:99: in function 'EnableElement' oUF_Adirelle\oUF\ouf.lua:269: in function <oUF_Adirelle\oUF\ouf.lua:192> (tail call): ? oUF_Adirelle\oUF\ouf.lua:555: in function 'Spawn' oUF_Adirelle\modules\arena\Layout.lua:67: in function 'func' oUF_Adirelle\oUF\factory.lua:20: in function <oUF_Adirelle\oUF\factory.lua:16> (tail call): ?`

The error does not appear to cause any negative effects on the rest of the addon however, so this could be a low priority.

**Comment by Adirelle** [comment]
See #8.
