### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by EthanCentaurai** [Adirelle/oUF_Adirelle#12]
Hello, sorry to trouble you again.

The GetRuneType() API was removed in 7.0.3 and logging in as a Death Knight produces the following error:

`
2x ...ns\oUF_Adirelle\modules\single\SecondaryPowerBar.lua:40: attempt to call upvalue 'GetRuneType' (a nil value)
...ns\oUF_Adirelle\modules\single\SecondaryPowerBar.lua:40: in function 'UpdateRuneColor'
oUF_Adirelle\elements\RuneBar.lua:45: in function <oUF_Adirelle\elements\RuneBar.lua:41>
oUF_Adirelle\elements\RuneBar.lua:66: in function 'func'
oUF_Adirelle\oUF\ouf.lua:158: in function 'UpdateAllElements'
oUF_Adirelle\oUF\ouf.lua:128: in function 'DisableElement'
...rfaceoUF_Adirelle\support\SavedVariables.lua:252: in function 'callback'
oUF_Adirelle\support\Messages.lua:42: in function <oUF_Adirelle\support\Messages.lua:40>
(tail call): ?
...rfaceoUF_Adirelle\support\SavedVariables.lua:336: in function 'func'
oUF_Adirelle\oUF\ouf.lua:273: in function <oUF_Adirelle\oUF\ouf.lua:192>
(tail call): ?
oUF_Adirelle\oUF\ouf.lua:555: in function 'Spawn'
oUF_Adirelle\modules\single\Layout.lua:35: in function 'Spawn'
oUF_Adirelle\modules\single\Layout.lua:44: in function func'
oUF_Adirelle\oUF\factory.lua:20: in function <oUF_Adirelle\oUF\factory.lua:16>
(tail call): ?
`

This error stopps the entire addon from working, however it can be solved by removing the local function UpdateRuneColor() block on lines 38 to 44 as well as the for loop on lines 51 to 53.

**Comment by Adirelle** [comment]
Has the rune system changed for DK in Legion ?

**Comment by Adirelle** [comment]
This fix prevents the color of the rune from being updated. Are all the rune the same color now ?

**Comment by EthanCentaurai** [comment]
Yes, they are. Death Knights now only have 1 type of Rune instead of 4 different ones.
