### ISSUE TITLE
Needs an update for 8.0

### ISSUE THREAD

**Issue by EthanCentaurai** [Adirelle/oUF_Adirelle#16]
Please. <3

I don't know oUF well enough to attempt it myself.

**Comment by Adirelle** [comment]
I have just subscribed for a month. I will try to get oufa to work again.

**Comment by EthanCentaurai** [comment]
So far so good on Hunter and Priest so far, though to be fair I didn't get to test much. Only issues I've noticed so far is the Twitch App isn't able to unzip the packages and the incoming heals don't appear to be showing. I'll be able to test more thoroughly over the weekend.

**Comment by EthanCentaurai** [comment]
So far the only things I've noticed are the shielded amount and heal prediction elements no longer show (or I've missed a setting somewhere). Thank you. :)
