### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by EthanCentaurai** [Adirelle/oUF_Adirelle#7]
Hello,

I am getting two errors when logging into my Priest with version 7.0-1.0.2 on the Curse App. I haven't tested other classes yet.

`1x oUF_Adirelle\support\Dispel.lua:42: bad argument #2 to 'band' (number expected, got nil)
[C]: in function 'band'
oUF_Adirelle\support\Dispel.lua:42: in main chunk`

which in turn causes

`4x oUF_Adirelle\elements\WarningIcon.lua:131: attempt to call field 'IsDispellable' (a nil value)
oUF_Adirelle\elements\WarningIcon.lua:131: in function 'getFunc'
oUF_Adirelle\elements\WarningIcon.lua:159: in function <oUF_Adirelle\elements\WarningIcon.lua:150>
oUF_Adirelle\elements\WarningIcon.lua:199: in function 'func'
oUF_Adirelle\oUF\ouf.lua:158: in function 'UpdateAllElements'
oUF_Adirelle\oUF\ouf.lua:128: in function 'DisableElement'
...rfaceoUF_Adirelle\support\SavedVariables.lua:252: in function 'callback'
oUF_Adirelle\support\Messages.lua:42: in function <oUF_Adirelle\support\Messages.lua:40>
(tail call): ?
...rfaceoUF_Adirelle\support\SavedVariables.lua:336: in function 'func'
oUF_Adirelle\oUF\ouf.lua:273: in function <oUF_Adirelle\oUF\ouf.lua:192>
(tail call): ?
oUF_Adirelle\oUF\ouf.lua:555: in function 'Spawn'
oUF_Adirelle\modules\single\Layout.lua:35: in function 'Spawn'
oUF_Adirelle\modules\single\Layout.lua:44: in function 'func'
oUF_Adirelle\oUF\factory.lua:20: in function <oUF_Adirelle\oUF\factory.lua:16>
(tail call): ?`

It looks like the C.TARGETING variable in LibPlayerSpells-1.0 either doesn't exist or is not populated properly when called.

These errors prevent the entire addon from working; no unit frames appear anywhere.

7.0-1.0.1 works fine.

**Comment by Adirelle** [comment]
Fixed in 7.0-1.0.3.
