### ISSUE TITLE
Unknown Spell on Warriors

### ISSUE THREAD

**Issue by EthanCentaurai** [Adirelle/oUF_Adirelle#8]
Hello,

Warriors appear to no longer have the Heroic Strike ability in 7.0.3 which causes this error on logging in:

`1x XRange:CheckSpell: unknown spell1 #78
oUF_Adirelle\elements\XRange.lua:147: in function <oUF_Adirelle\elements\XRange.lua:31>
oUF_Adirelle\elements\XRange.lua:225: in function <oUF_Adirelle\elements\XRange.lua:224>
oUF_Adirelle\elements\XRange.lua:238: in function 'enable'
oUF_Adirelle\oUF\ouf.lua:99: in function 'EnableElement'
oUF_Adirelle\oUF\ouf.lua:269: in function <oUF_Adirelle\oUF\ouf.lua:192>
(tail call): ?
oUF_Adirelle\oUF\ouf.lua:555: in function 'Spawn'
oUF_Adirelle\modules\arena\Layout.lua:67: in function 'func'
oUF_Adirelle\oUF\factory.lua:20: in function <oUF_Adirelle\oUF\factory.lua:16>
(tail call): ?`

The error does not appear to cause any negative effects on the rest of the addon however, so this could be a low priority.

**Comment by Adirelle** [comment]
This is related to the XRange element, which dims unit frames that are out of range. It tries to use character spells to get as accurate as possible. But some spells have been removed/restricted with 7.0 so it warns it cannot use them. #9 and #10 have the same cause.

The solution is to replace the missing spells with equivalent ones, i.e. with the same range and which work on the same kind of target (ally, enemy, pet, ...) in https://github.com/Adirelle/oUF_Adirelle/blob/master/elements/XRange.lua#L106.

**Comment by Adirelle** [comment]
I'm "merging" this into #13.
